package system:core;

record event-meta {
    id:        string,
    topic:     string,
    version:   u32,
    timestamp: u64,
}

world plugin-world {
    export handle-event: func(meta: event-meta, payload: list<u8>) -> result<_, string>;

    import emit-event: func(topic: string, payload: list<u8>);
}

world network-plugin-world {
    include plugin-world;

    import host-http-post: func(url: string, body: list<u8>) -> s32;
    import host-sse-start: func(url: string) -> s32;
}
