name: void

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install build tools
        run: |
          sudo apt-get install -y lld gcc-aarch64-linux-gnu

      - name: setup rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown, aarch64-unknown-linux-gnu, aarch64-linux-android

      - name: cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "void"

      - name: setup android ndk
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27c
          add-to-path: false

      - name: install cargo-ndk
        run: cargo install cargo-ndk

      - name: build plugins
        run: |
          cargo build -p plugin-crypto --target wasm32-unknown-unknown --release
          cargo build -p plugin-logger --target wasm32-unknown-unknown --release
          cargo build -p plugin-ntfy --target wasm32-unknown-unknown --release

      - name: build void (linux x64)
        env:
          RUSTFLAGS: "-C link-arg=-fuse-ld=lld"
        run: cargo build -p void --release

      - name: build void (android/aarch64)
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: cargo ndk --target aarch64-linux-android --platform 24 build -p void --release

      - name: package & test
        run: |
          mkdir -p dist/plugins
          mkdir -p dist/android
          
          cp target/release/void dist/
          cp target/wasm32-unknown-unknown/release/*.wasm dist/plugins/
          cp plugins/*.toml dist/plugins/
          
          cp target/aarch64-linux-android/release/void dist/android/
          
          cd dist
          chmod +x void
          echo "[TEST] Запуск проверки..."
          ./void <<EOF
          hello_from_github_actions
          /quit
          EOF

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: void
          path: dist/
